// Authentication Definitions
export const LOGIN_USER_ACTIVITY = 'LOGIN_USER_ACTIVITY';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const TOGGLE_SIGN_IN_MENU = 'TOGGLE_SIGN_IN_MENU';

// Search Results Definitions
export const BEGIN_FLIGHT_SEARCH = 'BEGIN_FLIGHT_SEARCH';

// Date Preferences Definitions
export const SWAP_DATES = 'SWAP_DATES';
export const TOGGLE_DEPART_DATE_MODAL = 'TOGGLE_DEPART_DATE_MODAL';
export const TOGGLE_RETURN_DATE_MODAL = 'TOGGLE_RETURN_DATE_MODAL';
export const UPDATE_DATE_FIELD = 'UPDATE_DATE_FIELD';

// Location Preferences Definitions
export const SWAP_LOCATIONS = 'SWAP_LOCATIONS';
export const UPDATE_LOCATION_FIELD = 'UPDATE_LOCATION_FIELD';

// Passenger Preferences Definitions
export const UPDATE_PASSENGER_FIELD = 'UPDATE_PASSENGER_FIELD';
export const INCREMENT_ADULT_COUNT = 'INCREMENT_ADULT_COUNT';
export const DECREMENT_ADULT_COUNT = 'DECREMENT_ADULT_COUNT';
export const INCREMENT_CHILD_COUNT = 'INCREMENT_CHILD_COUNT';
export const DECREMENT_CHILD_COUNT = 'DECREMENT_CHILD_COUNT';
export const INCREMENT_INFANT_COUNT = 'INCREMENT_INFANT_COUNT';
export const DECREMENT_INFANT_COUNT = 'DECREMENT_INFANT_COUNT';
export const RESET_PASSENGER_WARNING = 'RESET_PASSENGER_WARNING';

// Search Results Definitions
export const TOGGLE_SEARCH_LOADING = 'TOGGLE_SEARCH_LOADING';
export const POPULATE_AUTOCOMPLETE = 'POPULATE_AUTOCOMPLETE';

// Travel Preferences Definitions
export const TOGGLE_TRAVEL_MODE = 'TOGGLE_TRAVEL_MODE';
export const SEARCH_BY_AIRLINE = 'SEARCH_BY_AIRLINE';
export const SEARCH_DIRECT_FLIGHTS = 'SEARCH_DIRECT_FLIGHTS';
